# Generated by Django 4.2.14 on 2024-08-16 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeNumber', models.IntegerField(max_length=10)),
                ('lastName', models.CharField(max_length=200)),
                ('firstName', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('role', models.CharField(max_length=200)),
                ('reportsTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.employee')),
            ],
        ),
    ]
