# Generated by Django 4.2.14 on 2024-08-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_employee_employeenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeNumber',
            field=models.CharField(max_length=10),
        ),
    ]
