# Generated by Django 4.2.14 on 2024-08-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_employee_employeenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeNumber',
            field=models.IntegerField(),
        ),
    ]
