# Generated by Django 4.2.14 on 2024-08-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_employee_employeenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='reportsTo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
